stages:
  - build-front
  - populate
  - build-docker
  - deploy

variables:
    DOCKER_HOST: tcp://docker:2375

build-frontend:
  image: node:13.4.0
  stage: build-front
  script:
    - npm install --prefix frontend
    - npm run build --prefix frontend
  artifacts:
    paths:
      - frontend/build

parse-files:
  image: golang:latest
  stage: populate
  script:
    - cd backend
    - go run main.go -populate
  artifacts:
    paths:
      - backend/types.json

build-site:
  image: docker:dind
  stage: build-docker
  dependencies:
    - parse-files
    - build-frontend
  script:
    - docker build ./backend
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push smanierre/typer-site
