stages:
  - build-front
  - populate
  - build-back
  - build-docker
  - deploy

variables:
    DOCKER_HOST: tcp://docker:2375

services:
    - docker:dind
 
build-frontend:
  image: node:13.4.0
  stage: build-front
  script:
    - npm install --prefix frontend
    - npm run build --prefix frontend
  artifacts:
    paths:
      - frontend/build

parse-files:
  image: golang:latest
  stage: populate
  script:
    - cd backend
    - go run main.go -populate
  artifacts:
    paths:
      - backend/types.json

build-binary:
  image: golang:latest
  stage: build-back
  script:
    - cd backend
    - CGO_ENABLED=0 GOOS=linux && go build -o typersite .
  artifacts:
    paths:
      - backend/typersite

build-site:
  image: docker
  stage: build-docker
  dependencies:
    - parse-files
    - build-frontend
  script:
    - mkdir backend/static
    - cp -rp frontend/build/* backend/static
    - cd backend
    - ls
    - cd static
    - ls
    - cd ..
    - docker build .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push smanierre/typer-site
