stages:
  - build
variables:
  DOCKER_HOST: tcp://docker:2375
build-apptainer:
  image: docker
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t smanierre/typer-site:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push -a smanierre/typer-site
  artifacts:
    paths:
      - .env