image: golang:latest

stages:
  - build-front
  - populate
  - build-back
  - deploy

build-frontend:
  image: node:13.4.0
  stage: build-front
  script:
    - npm install --prefix frontend
    - npm run build --prefix frontend
  artifacts:
    paths:
      - frontend/build

parse-files:
  stage: populate
  script:
    - cd backend
    - go run main.go -populate
  artifacts:
    paths:
      - backend/types.json

build-site:
  stage: build-back
  dependencies:
    - parse-files
    - build-frontend
  script:
    - mkdir prod
    - mkdir prod/static
    - cp backend/types.json prod
    - cp -r frontend/build/* prod/static
    - cp backend/start.sh prod
    - cd backend
    - CGO_ENABLED=0
    - GOOS=linux
    - go build -o ../prod/typer-site .
    - cd ..
    - printf "DB_HOST=$DB_HOST\nDB_NAME=$DB_NAME\nDB_PASSWORD=$DB_PASSWORD\nDB_PORT=$DB_PORT\nDB_USER=$DB_USER" > prod/.env
  artifacts:
    paths:
      - prod
