image: golang:latest

stages:
  - build-front
  - populate
  - build-back
  - deploy

build-frontend:
  image: node:13.4.0
  stage: build-front
  script:
    - npm install --prefix frontend
    - npm run build --prefix frontend
    - cp -r frontend/build/* backend/static
  artifacts:
    paths:
      - frontend/build

parse-files:
  stage: populate
  script:
    - cd backend
    - go build -o=parser .
    - ./parser -populate
  artifacts:
    paths:
      - backend/types.json

build-site:
  stage: build-back
  dependencies:
    - parse-files
    - build-frontend
  script:
    - ls
