version: "3.7"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        expose: 
            - '5432'
    web:
        build: .
        depends_on: 
            - db
        ports:
            - '4000:8080'